POST http://localhost:7071/api/devices/register HTTP/1.1
content-type: application/json

{
  "id": "EMP-1043",
  "name": "Nico Vermeir",
  "email": "nico.vermeir@proximus.be",
  "department": "Proximus",
  "role": "Technican",
  "startDate": "2026-08-22",
  "status": "Pending",
  "manager": "Karim",
  "description": "",
  "createdAt": "2026-06-15",
  "source": "pxs-workflows",
  "submittedAt": "2026-06-15T12:34:20.698Z"
}

###

POST http://localhost:7071/api/employees/generate-id HTTP/1.1
content-type: application/json

{
  "id": "",
  "name": "Nico Vermeir",
  "email": "nico.vermeir@proximus.be",
  "department": "Proximus",
  "role": "Technican",
  "startDate": "2026-08-22",
  "status": "Pending",
  "manager": "Karim",
  "description": "",
  "createdAt": "2026-06-15",
  "source": "pxs-workflows",
  "submittedAt": "2026-06-15T12:34:20.698Z"
}